baseURL = 'https://23chase.github.io/'
languageCode = 'en-us'
title = 'Mark Mukhin'
theme = 'hugo-bearblog-master'

author = "Mark Mukhin"
copyright = "Copyright Â© 2022, Mark Mukhin."
enableRobotsTXT = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/texts/:slug"

  [params]
    description = "Ideas pop into my head and I pursue them. Some are converted into texts. I work long-term, and compound concepts. Join, if you wanna."
    favicon = "images/favicon.png"
    images = ["images/share.png"]
    title = "Mark Mukhin"

hideMadeWithLine = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
